from turtle import Turtle, Screen
import time
import random

wn = Screen()
wn.setup(width=1000, height=1100
         )
wn.bgcolor('lightblue')
#user_bet = wn.textinput(title='Turtle Race', prompt="Choose your turtle by color")
#####################################################
tracy = Turtle()
tracy.shape('turtle')
referee = tracy.clone()
huy = tracy.clone()
jay = tracy.clone()
khang = tracy.clone()
tuan = tracy.clone()
peardyn = tracy.clone()
######################################################
referee.color('black')
tracy.color('red')
huy.color('blue')
jay.color('green')
khang.color('brown')
peardyn.color('purple')
tuan.color('orange')
######################################################
referee.up()
tracy.up()
tuan.up()
peardyn.up()
khang.up()
jay.up()
huy.up()
#######################################################
referee.goto(-400, 0)
referee.write("Referee", move=False, align='center', font=('Italic', 25, 'normal'))
tracy.goto(-400, 450)
tracy.write("Tracy", move=False, align='center', font=('Italic', 25, 'normal'))
tuan.goto(-400, 300)
tuan.write("Tuan", move=False, align='center', font=('Italic', 25, 'normal'))
peardyn.goto(-400, 150)
peardyn.write("Peardyn", move=False, align='center', font=('Italic', 25, 'normal'))
khang.goto(-400, -150)
khang.write("KevBui", move=False, align='center', font=('Italic', 25, 'normal'))
jay.goto(-400, -300)
jay.write("Jay", move=False, align='center', font=('Italic', 25, 'normal'))
huy.goto(-400, -450)
huy.write("Huy", move=False, align='center', font=('Italic', 25, 'normal'))
#################################################
referee.down()
tracy.down()
tuan.down()
peardyn.down()
khang.down()
jay.down()
huy.down()
##########################################################################
referee.penup()
referee.color("black")
referee.pensize(10)
referee.goto(400, -490)
referee.left(90)
referee.down()
referee.forward(970)
referee.write("Finish", move=False, align='center', font=('Arial', 30, 'normal'))
referee.up()
referee.goto(-400, 0)
referee.right(90)
referee.down()
referee.pensize(5)
referee.forward(800)
referee.up()
referee.goto(-400, 0)
####################################################################
a_die = [1, 2, 3, 4, 5, 6]
for i in range(50):
    if tracy.pos() >= (400, -490):
        tracy.hideturtle()
        tracy.up()
        tracy.goto(0, 0)
        style = ('Courier', 30, 'italic')
        tracy.color("red")
        time.sleep(0.25)
        tracy.write(f"Victory for Tracy!!!", font=style, align='center')
        break

    elif khang.pos() >= (400, -490):
        khang.hideturtle()
        khang.up()
        khang.goto(0, 0)
        style = ('Courier', 30, 'italic')
        khang.color("brown")
        time.sleep(0.25)
        khang.write(f"Victory for KevBui!!!", font=style, align='center')
        break
    elif peardyn.pos() >= (400, -490):
        peardyn.hideturtle()
        peardyn.up()
        peardyn.goto(0, 0)
        style = ('Courier', 30, 'italic')
        peardyn.color("purple")
        time.sleep(0.25)
        peardyn.write(f"Victory for Peardyn!!!", font=style, align='center')
        break
    elif tuan.pos() >= (400, -490):
        tuan.hideturtle()
        tuan.up()
        tuan.goto(0, 0)
        style = ('Courier', 30, 'italic')
        tuan.color("orange")
        time.sleep(0.25)
        tuan.write(f"Victory for Tuan!!!", font=style, align='center')
        break
    elif huy.pos() >= (400, -490):
        huy.hideturtle()
        huy.up()
        huy.goto(0, 0)
        style = ('Courier', 30, 'italic')
        huy.color("blue")
        time.sleep(0.25)
        huy.write(f"Victory for Huy!!!", font=style, align='center')
        break
    elif jay.pos() >= (400, -490):
        jay.hideturtle()
        jay.up()
        jay.goto(0, 0)
        style = ('Courier', 30, 'italic')
        jay.color("red")
        time.sleep(0.25)
        jay.write(f"Victory for Tracy!!!", font=style, align='center')
        break
    die_roll = random.choice(a_die)
    tracy.forward(30 * die_roll)
    time.sleep(0.25)
    die_roll3 = random.choice(a_die)
    khang.forward(30 * die_roll3)
    time.sleep(0.25)
    die_roll4 = random.choice(a_die)
    peardyn.forward(30 * die_roll4)
    time.sleep(0.25)
    die_roll2 = random.choice(a_die)
    tuan.forward(30 * die_roll2)
    time.sleep(0.25)
    die_roll6 = random.choice(a_die)
    huy.forward(30 * die_roll6)
    time.sleep(0.25)
    die_roll5 = random.choice(a_die)
    jay.forward(30 * die_roll5)
    time.sleep(0.25)

wn.exitonclick()
